version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
    

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    # ports:
    #   - 27018:27017

volumes:
  mongo_data:
